services:
  - type: web
    name: matekids-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn matekids-app:main --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.6"
    plan: free
    