"""Sistema de traducciones para MateKids - Soporta Español e Inglés"""

TRANSLATIONS = {
    "es": {
        # Login
        "welcome": "¡Bienvenido!",
        "choose_avatar": "Elige tu avatar",
        "your_name": "¿Cómo te llamas?",
        "start_playing": "¡Empezar a jugar!",
        "name_required": "Escribe tu nombre",
        
        # Home
        "greeting": "Hola",
        "stars": "Estrellas",
        "choose_level": "Elige un nivel",
        "level_1": "🟢 Nivel 1",
        "level_2": "🔵 Nivel 2",
        "level_3": " Nivel 3",
        "generate_pdf": "📚 Generar Cuadernillo PDF",
        "pdf_saved": "✅ PDF guardado en: data/",
        "pdf_error": "❌ Error al generar PDF",
        "no_activities": "⚠️ No hay actividades para este nivel",
        
        # Game
        "very_good": "⭐ ¡Muy bien! ⭐",
        "try_again": "🤔 Intenta otra vez",
        "almost": "Casi. Contemos otra vez.",
        
        # Results
        "congratulations": "🏆 ¡Felicidades",
        "good_job": "🎯 Buen trabajo",
        "finished": "🏆 ¡Terminaste!",
        "got_stars": "Conseguiste",
        "stars_in_level": "estrellas en el nivel",
        "generate_diploma": "🏆 Generar mi Diploma",
        "diploma_saved": "✅ ¡Diploma guardado en: data/",
        "diploma_error": "❌ Error al generar diploma",
        "back_home": "Volver al Inicio 🏠",
        
        # Diploma
        "diploma_title": "DIPLOMA DE RECONOCIMIENTO",
        "diploma_subtitle": "Se otorga el presente reconocimiento a:",
        "completed_level": "Por haber completado exitosamente el Nivel",
        "with_grade": "con una calificación de",
        "stars_text": "estrellas",
        "date": "Fecha",
        "teacher_signature": "Firma del Maestro/a",
        "footer": "🎓 Generado por MateKids - ¡Aprender es divertido! 🎓",
        
        # PDF Workbook
        "workbook_title": "Cuadernillo de Matemáticas - Nivel",
        "workbook_subtitle": "Resuelve los siguientes ejercicios",
    },
    
    "en": {
        # Login
        "welcome": "Welcome!",
        "choose_avatar": "Choose your avatar",
        "your_name": "What's your name?",
        "start_playing": "Start Playing!",
        "name_required": "Please enter your name",
        
        # Home
        "greeting": "Hello",
        "stars": "Stars",
        "choose_level": "Choose a level",
        "level_1": "🟢 Level 1",
        "level_2": "🔵 Level 2",
        "level_3": " Level 3",
        "generate_pdf": "📚 Generate Workbook PDF",
        "pdf_saved": "✅ PDF saved in: data/",
        "pdf_error": "❌ Error generating PDF",
        "no_activities": "⚠️ No activities for this level",
        
        # Game
        "very_good": "⭐ Very Good! ⭐",
        "try_again": "🤔 Try Again",
        "almost": "Almost. Let's count again.",
        
        # Results
        "congratulations": "🏆 Congratulations",
        "good_job": "🎯 Good Job",
        "finished": "🏆 You Finished!",
        "got_stars": "You got",
        "stars_in_level": "stars in level",
        "generate_diploma": "🏆 Generate My Diploma",
        "diploma_saved": "✅ Diploma saved in: data/",
        "diploma_error": "❌ Error generating diploma",
        "back_home": "Back to Home ",
        
        # Diploma
        "diploma_title": "CERTIFICATE OF ACHIEVEMENT",
        "diploma_subtitle": "This certificate is awarded to:",
        "completed_level": "For successfully completing Level",
        "with_grade": "with a score of",
        "stars_text": "stars",
        "date": "Date",
        "teacher_signature": "Teacher's Signature",
        "footer": "🎓 Generated by MateKids - Learning is Fun! 🎓",
        
        # PDF Workbook
        "workbook_title": "Math Workbook - Level",
        "workbook_subtitle": "Solve the following exercises",
    }
}

def get_text(lang: str, key: str) -> str:
    """Obtiene texto traducido. Si no existe, devuelve en inglés como fallback."""
    if lang not in TRANSLATIONS:
        lang = "en"
    return TRANSLATIONS.get(lang, {}).get(key, TRANSLATIONS["en"].get(key, key))

def get_available_languages() -> list:
    """Retorna lista de idiomas disponibles."""
    return list(TRANSLATIONS.keys())